# 端口
server:
  port: 8081


spring:
  profiles:
    active: dev

  #redis配置 和车白问使用同一个redis
  redis:
    open: false # 是否开启redis缓存  true开启   false关闭
    timeout: 6000 # 连接超时时长（毫秒）
    jedis:
      pool:
        max-active: 1000 # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1ms # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10 # 连接池中的最大空闲连接
        min-idle: 5 # 连接池中的最小空闲连接

# MyBatis设置
mybatis-plus:
  # 搜索指定包别名
  typeAliasesPackage: com.advertisement.domain
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapper-locations: classpath*:/mapper/*.xml
  # 全局配置
  global-config:
    db-config:
      #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID", ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: auto
